jobs:
  include:
  - stage: test
    language: node_js
    node_js: '11'
    services:
    - docker
    install:
    - docker pull vanbujm/moonbase-balena:v0.1.0-ci-v0.2.15
    script:
    - docker run -v $(pwd):/app -v $(yarn cache dir):/yarn-cache -e CODECOV_TOKEN="$CODECOV_TOKEN"
      vanbujm/moonbase-balena:v0.1.0-ci-v0.2.15 -c "cd /app && yarn --cache-folder  /yarn-cache --ignore-scripts
      && ./bin/setup-arm.sh && yarn test-ci && codecov"
    cache:
      yarn: true
stages:
- test
notifications:
  slack:
    secure: HrVuO23sddenqdF4H720qs4JJmtCSJOShVPdu7qH0ZgT+ccOi482vDNPIU7RvIXrEt/av9/qB+GzkFg+iIT1lXPQ7U0YelQys9U9y9DlzZzqJeSE5L4uzLBmv6AeGzK7hrXzhznZIowfo1Pk4n0MP/dfsF7G3HbYSkCN80ERgY8xHuGQn2cRYmOK41HmsKKVk+RlQtBaeST7uX6tVKYkLIt7ucSYG5BRzsH41p4c7XZJNPIk3zNU8yn68Zb1ZgmbZqeEBM2DSs2MOAeaCVS9sPjh/mIU0tTutevS0z1dP3P22Rt/n07dnnJ71/nMHkmeg8nxLPNkI72U/ELFbIw6HjizPODTJF4EjB3vyLVfDjg4kfeBy6k5sqR8qbbDhGhdlHzd4qZXpkqgsh15ZhSp3MNCQwu0O1oOfRfvsnhuA93zVpm/Zyv8OGjeNIeUslgXpZYs3c/ibIBN1DhStW2V1LWWj6rIlu3hLoLqLan06O9aTavxEvs0/6Pa9L8svQiA6Lacogld5cr/Cc7Ej/JkLQ9Clrrs+BshqJjW3NxR9DPB1cfcwMJZhNiY8nWbi4kKBX8069XhaQqp5qM9lZgsgdBCmP37+Jw5fJP70xeGwF25TUIIh5dU9w9iBNNbbT9tV07bdffQEdxyjGadhAZkHRtNUkIcmoA+ooMGpwFmhsY=
